# Generated by Django 5.2.4 on 2025-09-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_area',
            field=models.CharField(blank=True, choices=[('HKD', '北海道'), ('AOM', '青森県'), ('IWT', '岩手県'), ('MYG', '宮城県'), ('AKT', '秋田県'), ('YMGT', '山形県'), ('FKSM', '福島県'), ('IBRK', '茨城県'), ('TTG', '栃木県'), ('GNM', '群馬県'), ('SITM', '埼玉県'), ('CB', '千葉県'), ('TKY', '東京都'), ('KNGW', '神奈川県'), ('NIGT', '新潟県'), ('TYM', '富山県'), ('ISKW', '石川県'), ('FKI', '福井県'), ('YMNS', '山梨県'), ('NGN', '長野県'), ('GF', '岐阜県'), ('SZOK', '静岡県'), ('AIC', '愛知県'), ('ME', '三重県'), ('SIG', '滋賀県'), ('KYT', '京都府'), ('OSK', '大阪府'), ('HYG', '兵庫県'), ('NR', '奈良県'), ('WKYM', '和歌山県'), ('TTR', '鳥取県'), ('SMN', '島根県'), ('OKYM', '岡山県'), ('HRSM', '広島県'), ('YMGT', '山口県'), ('TKSM', '徳島県'), ('KGW', '香川県'), ('AIC', '愛媛県'), ('KOC', '高知県'), ('FKOK', '福岡県'), ('SAG', '佐賀県'), ('NGSK', '長崎県'), ('KMMT', '熊本県'), ('OIT', '大分県'), ('MYZK', '宮崎県'), ('KGSM', '鹿児島県'), ('OKNW', '沖縄県')], max_length=10),
        ),
    ]
