# Generated by Django 5.2.4 on 2025-09-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'いいねされました'), ('match', 'マッチしました'), ('message', 'メッセージが届きました')], max_length=10),
        ),
    ]
